import {
  ETHEREUM_MAINNET,
  ETHEREUM_ROPSTEN,
  ETHEREUM_RINKEBY,
  ETHEREUM_GOERLI,
  ETHEREUM_KOVAN,
  BINANCE_MAINNET,
  BINANCE_TESTNET,
  MATIC_MAINNET,
  MUMBAI_TESTNET,
} from './evm-standard-networks'

import {
  ETHEREUM_MAINNET_CHAIN,
  ETHEREUM_ROPSTEN_CHAIN,
  ETHEREUM_RINKEBY_CHAIN,
  ETHEREUM_GOERLI_CHAIN,
  ETHEREUM_KOVAN_CHAIN,
  BSC_MAINNET_CHAIN,
  BSC_TESTNET_CHAIN,
  POLYGON_MAINNET,
  POLYGON_MUMBAI,
} from './evm-standard-networks'

export const allChains = {
  [ETHEREUM_MAINNET]: ETHEREUM_MAINNET_CHAIN,
  [ETHEREUM_ROPSTEN]: ETHEREUM_ROPSTEN_CHAIN,
  [ETHEREUM_RINKEBY]: ETHEREUM_RINKEBY_CHAIN,
  [ETHEREUM_GOERLI]: ETHEREUM_GOERLI_CHAIN,
  [ETHEREUM_KOVAN]: ETHEREUM_KOVAN_CHAIN,
  [BINANCE_MAINNET]: BSC_MAINNET_CHAIN,
  [BINANCE_TESTNET]: BSC_TESTNET_CHAIN,
  [MATIC_MAINNET]: POLYGON_MAINNET,
  [MUMBAI_TESTNET]: POLYGON_MUMBAI,
}

// export con
